// <auto-generated />
using Final_Project_Civ_Mayor_Civilization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    partial class WorldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("MyProject.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefensePower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnsSinceLastProduce")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Buildings", (string)null);

                    b.HasDiscriminator<string>("BuildingType").HasValue("Building");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyProject.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resources", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.TerrainFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TerrainFeatures", (string)null);
                });

            modelBuilder.Entity("MyProject.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CTasks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefensePower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastGatheredResource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastGatheredTerrain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);

                    b.HasDiscriminator<string>("UnitType").HasValue("Unit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyProject.Models.House", b =>
                {
                    b.HasBaseType("MyProject.Models.Building");

                    b.HasDiscriminator().HasValue("House");
                });

            modelBuilder.Entity("MyProject.Models.TownCenter", b =>
                {
                    b.HasBaseType("MyProject.Models.Building");

                    b.HasDiscriminator().HasValue("TownCenter");
                });

            modelBuilder.Entity("MyProject.Models.Barbarian", b =>
                {
                    b.HasBaseType("MyProject.Models.Unit");

                    b.HasDiscriminator().HasValue("Barbarian");
                });

            modelBuilder.Entity("MyProject.Models.Scout", b =>
                {
                    b.HasBaseType("MyProject.Models.Unit");

                    b.HasDiscriminator().HasValue("Scout");
                });

            modelBuilder.Entity("MyProject.Models.Villager", b =>
                {
                    b.HasBaseType("MyProject.Models.Unit");

                    b.HasDiscriminator().HasValue("Villager");
                });
#pragma warning restore 612, 618
        }
    }
}
